apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cli-proxy-api
  namespace: ai
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - cpa.cocox.ai
      secretName: cocox-ai-wildcard-cert-manager
  rules:
    - host: cpa.cocox.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cli-proxy-api
                port:
                  number: 8310
